---
apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: tekton-instana-version-resource-pipeline
spec:
  params:
    - name: branch
      type: string
      default: "main"
  workspaces:
    - name: output
  tasks:
    - name: git-clone
      taskRef:
        name: git-clone
      workspaces:
        - name: output
      params:
        - name: url
          value: "https://github.com/instana/instana-version-resource.git"
        - name: revision
          value: $(params.branch)
        - name: deleteExisting
          value: "true"

    - name: build-instana-version-resource-image
      taskSpec:
        params:
          - name: cloned-dir
            type: string
            value: instana-version-resource
        steps:
          - name: build-instana-version-resource-image
            image: icr.io/instana/oci-build-task:latest
            script: |
              docker build -t instana-version-resource:latest $(params.cloned-dir) 
              docker save -o /workspace/output/instana-version-resource.tar instana-version-resource:latest
        workspaces:
          - name: output
      runAfter:
        - git-clone
      params:
        - name: cloned-dir
          value: /workspace/output/instana-version-resource
      

    - name: publish-instana-version-resource-image
      taskSpec:
        params:
          - name: image-tar
            type: string
        steps:
          - name: publish-instana-version-resource-image
            image: icr.io/instana/instana-version-resource:latest
            script: |
              docker load -i $(workspaces.output.path)/instana-version-resource.tar
              docker tag instana-version-resource:latest icr.io/instana/instana-version-resource:latest
              docker push icr.io/instana/instana-version-resource:latest
        workspaces:
          - name: output
      runAfter:
        - build-instana-version-resource-image
